:root {
	--main-color: #e41b1b;
	--hover-color: #991a1a;
    --background-brightness: 100%;
}

body::after,
.callout-backdrop,
.user-popout::before,
#user-profile-modal .header::before,
#pubs-container::before,
.auth-background,
.auth-tiling-bg,
.invite-modal .invite-splash,
.radio-theme.light label,
.radio-theme.dark label{
    background-image: url(https://i.ytimg.com/vi/F0RT8g2fPUA/maxresdefault.jpg) !important; /* IMPORTANT: Link must be HTTPS! */
}

